import json
import re
from pathlib import Path

from pypdf import PdfReader


ROOT = Path(__file__).resolve().parents[1]
PDF_DIR = ROOT / "docs"
OUTPUT = ROOT / "document-snippets.js"


def first_sixteen_characters(pdf_path: Path) -> str:
    reader = PdfReader(str(pdf_path))
    text = "".join(page.extract_text() or "" for page in reader.pages)
    text = re.sub(r"\s+", " ", text).strip()
    text = re.sub(r"^[（(]\s*(?:\d\s*)+[）)]\s*", "", text)
    return text[:16].strip()


snippets = {
    pdf_path.stem: first_sixteen_characters(pdf_path)
    for pdf_path in sorted(PDF_DIR.glob("*.pdf"))
}

payload = json.dumps(snippets, ensure_ascii=False, indent=2)
OUTPUT.write_text(
    "// Generated by scripts/generate_document_snippets.py\n"
    f"window.DOCUMENT_SNIPPETS = {payload};\n",
    encoding="utf-8",
)

print(f"Generated {len(snippets)} document headings in {OUTPUT.name}")
