import json
import re
from pathlib import Path

from pypdf import PdfReader


ROOT = Path(__file__).resolve().parents[1]
PDF_DIR = ROOT / "docs"
OUTPUT = ROOT / "korean-expressions.js"

# A small, deliberately familiar glossary. These concepts repeat throughout
# the source texts and are easier to review than a whole sentence.
GLOSSARY = [
    ("하늘부모님", "天の父母様"), ("참부모님", "真の父母様"),
    ("독생녀", "ひとり娘"), ("독생자", "ひとり子"),
    ("한민족", "韓民族"), ("대한민국", "大韓民国"),
    ("한반도", "朝鮮半島"), ("기독교", "キリスト教"),
    ("불교", "仏教"), ("유교", "儒教"), ("하나님", "神"),
    ("환웅", "桓雄"), ("호랑이", "虎"), ("곰", "熊"),
    ("한글", "ハングル"), ("자음", "子音"), ("모음", "母音"),
    ("발음", "発音"), ("일본군", "日本軍"), ("김일성", "金日成"),
    ("역사", "歴史"), ("인류", "人類"), ("민족", "民族"),
    ("세계", "世界"), ("평화", "平和"), ("사랑", "愛"),
    ("희망", "希望"), ("문화", "文化"), ("전통", "伝統"),
    ("정체성", "アイデンティティ"), ("신앙", "信仰"),
    ("가정", "家庭"), ("가족", "家族"), ("조국", "祖国"),
    ("한국", "韓国"), ("조선", "朝鮮"), ("독립", "独立"),
    ("통일", "統一"), ("자유", "自由"), ("정의", "正義"),
    ("생명", "生命"), ("창조", "創造"), ("미래", "未来"),
    ("꿈", "夢"), ("비전", "ビジョン"), ("지혜", "知恵"),
    ("도덕", "道徳"), ("책임", "責任"), ("역할", "役割"),
    ("교육", "教育"), ("지도자", "指導者"), ("발전", "発展"),
    ("사회", "社会"), ("국가", "国家"), ("인간", "人間"),
    ("마음", "心"), ("감사", "感謝"), ("효정", "孝情"),
    ("축복", "祝福"), ("하늘", "天・空"),
]


def korean_sentences(pdf_path: Path) -> list[str]:
    text = "\n".join(page.extract_text() or "" for page in PdfReader(str(pdf_path)).pages)
    lines = []
    for raw_line in text.splitlines():
        line = re.sub(r"\s+", " ", raw_line).strip()
        if len(re.findall(r"[가-힣]", line)) >= 6 and not re.search(r"[ぁ-んァ-ン]", line):
            lines.append(line)
    return [
        sentence.strip()
        for line in lines
        for sentence in re.split(r"(?<=[.!?])\s+", line)
        if len(re.findall(r"[가-힣]", sentence)) >= 6
    ]


def short_example(sentence: str) -> str:
    sentence = re.sub(r"^[（(][0-9 ]+[）)]\s*", "", sentence).strip()
    sentence = re.sub(r"\s+([.!?])", r"\1", sentence)
    return sentence if len(sentence) <= 42 else sentence[:41].rstrip() + "…"


document_sentences = [
    korean_sentences(pdf_path)
    for pdf_path in sorted(PDF_DIR.glob("*.pdf"), key=lambda path: int(path.stem))
]

# Keep one representative example for each glossary word.  The page rotates
# through this list, so common concepts do not appear again for about a month.
words = []
for word, meaning in GLOSSARY:
    example = next(
        (
            sentence
            for sentences in document_sentences
            for sentence in sentences
            if word in sentence
        ),
        None,
    )
    if example:
        words.append({"word": word, "meaning": meaning, "example": short_example(example)})

OUTPUT.write_text(
    "// Generated by scripts/generate_korean_expressions.py\n"
    f"window.KOREAN_WORD_LIST = {json.dumps(words, ensure_ascii=False, indent=2)};\n",
    encoding="utf-8",
)

print(f"Generated {len(words)} unique Korean words in {OUTPUT.name}")
